version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
  - rotespferd
  labels:
  - dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  commit-message:
    prefix: fix
    prefix-development: chore

- package-ecosystem: npm
  directory: "/api"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - rotespferd
  labels:
  - dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  commit-message:
    prefix: fix
    prefix-development: chore
    
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - rotespferd
  labels:
  - dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  commit-message:
    prefix: fix
    prefix-development: chore
    
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"