version: "3.1"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kennsla
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: kennsla

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080