// Creating tables
Table teacher as t {
  id int [pk, increment] // auto-increment
  firstname varchar
  lastname varchar
  school int
}

Table school as s {
  id int [pk, increment]
  name varchar
 }

Table worksheet {
  id int [pk, increment]
  title varchar
  teacher_id int
}
 
Table task {
  id int [pk, increment]
  title varchar
}

Table contentblock {
  id int [pk, increment]
  type varchar
  payload xml
}

Table hint {
  id int [pk, increment]
  title varchar
  task_id int
}

Table solution {
  id int [pk, increment]
  text varchar
  
  task_id int
}

Table solution_submission {
  id int [pk, increment]
  result varchar
  timestamp datetime
  solution_id int
}

// Many-to-Many
Table worksheet_task {
  worksheet_id int
  task_id int
  order int
}

Table task_contentblock {
  contentblock_id int
  task_id int
  order int
}

Table hint_contentblock {
  contentblock_id int
  hint_id int
  order int
}

// Creating references

// > many-to-one; < one-to-many; - one-to-one
Ref: s.id < t.school
Ref: t.id > worksheet.teacher_id

Ref: worksheet.id > worksheet_task.worksheet_id
Ref: task.id > worksheet_task.task_id

Ref: contentblock.id > task_contentblock.contentblock_id
Ref: task.id > task_contentblock.task_id
Ref: task.id < hint.task_id

Ref: contentblock.id > hint_contentblock.contentblock_id
Ref: hint.id > hint_contentblock.hint_id

Ref: task.id - solution.id
Ref: solution.id < solution_submission.solution_id