# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Monorepo

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: node common/scripts/install-run-rush.js install
              name: Install dependencies

            - run: node common/scripts/install-run-rush.js rebuild --verbose
              name: Build dependencies

            - run: node common/scripts/install-run-rush.js analyze
              name: Analyze dependencies

            - run: node common/scripts/install-run-rush.js test
              name: Test projects
