name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      message:
        required: false
        description: 'Build description'

  workflow_run:
    workflows: ["CI Frontend"]
    type:
      - complete

jobs:
  deployment:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://kennsla-frontend.netlify.app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - run: npm run build
        name: Build SvelteKit
        working-directory: frontend
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npm run deploy:prod
        working-directory: frontend