# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development Server

on:
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

env:
  GO_VERSION: 1.17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: go build -v ./...
      working-directory: server

    - name: Test
      run: go test -v ./test/...
      working-directory: server
