# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development Frontend

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.1.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - run: npm ci
      name: Install Node dependencies in frontend folder
      working-directory: frontend
      
    - run: npm run build
      name: Build SvelteKit
      working-directory: frontend

  check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.1.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - run: npm ci
      name: Install Node dependencies in frontend folder
      working-directory: frontend
      
    - run: npm run check
      name: Check code
      working-directory: frontend

    - run: npm run lint
      name: Lint code
      working-directory: frontend

  test:
    runs-on: ubuntu-latest
    needs: [build, check]

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      VITE_API_URL: http://localhost:1323
      VITE_API_KEY: AAAAAAAAAAAAAAAA
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.1.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Build the docker-compose stack
      run: cp config_dist.toml ../server/config.toml && cp config_dist.toml config.toml && docker-compose build
      working-directory: frontend
    - name: Run migration in docker-compose
      run: docker-compose run api ./server migrate
      working-directory: frontend
    - name: Run docker-compose
      run: docker-compose up -d
      working-directory: frontend

    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    - name: Install Playwright
      run: npx playwright install --with-deps
      working-directory: frontend
    
    - name: Run your tests
      run: npm test
      working-directory: frontend
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-results
        path: frontend/test-results
