# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development Server

on:
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

env:
  DENO_VERSION: v1.20.x

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

  test:
    runs-on: ubuntu-latest

    needs: [ check ]

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Run tests
        run: deno test -A --unstable